# Builds the docs using mkdocs and pushes the result to `gh-pages` branch.
name: Docs
run-name: Build Docs 📄
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install Requirements
        run: |
          sudo apt-get update &&
          sudo apt-get install pngquant &&
          pip install mkdocs-material mkdocs-material-extensions pillow cairosvg
      - name: Build and deploy MkDocs
        run: mkdocs gh-deploy --force
